### PR TITLE
Update balls.asm

### PR DESCRIPTION
**Pull request by ballsballsballsballsballsballsballsball**
@qexat is this yes

### CODE REVIEW

**Comment by jaculate** [comment]
No

**Comment by ballsballsballsballsballsballsballsball** [comment]
> No

How do I ban you

**Comment by jaculate** [comment]
I don't know

**Comment by jaculate** [comment]
Pleae do not the cat

**Comment by qexat** [comment]
Correct but please make the indentation consistent 😭

**Comment by jaculate** [comment]
Why

**Comment by qexat** [comment]
> Why

It is faster

**Comment by ballsballsballsballsballsballsballsball** [comment]
> Correct but please make the indentation consistent 😭

I have farted the indentation

**Pull request merged**
