### PR TITLE
new line please and also correct return type

### PR DESCRIPTION
**Pull request by ceilingfans**
bruh moment did not c plus plus correctly what the hell is this why is the return type void when the code returns 0 at the end why WHY WHY

IT ALSO NOT PRUINT NEW LINE WTFFFF

### CODE REVIEW

**Comment by ceilingfans** [comment]
Screenshot 2022-03-19 at 12 20 09 PM

so annoy...

**Comment by jaculate** [comment]
Sorry i made when just start C++ So sorry

**Review by jaculate — APPROVED** [review]

**Comment by ballsballsballsballsballsballsballsball** [comment]
I invented c

**Comment by ballsballsballsballsballsballsballsball** [comment]
Okay @jaculate please test contribut next time

**Comment by jaculate** [comment]
Ok

**Pull request merged**
