### PR TITLE
balls-to-the-infinity.py

### PR DESCRIPTION
**Pull request by giorno420**
do not try this at home

also I don't know ajax and I'm new to javascript that's why this code only works in theory

### CODE REVIEW

**Comment by ballsballsballsballsballsballsballsball** [comment]
What the fuck is that

**Comment by ceilingfans** [comment]
Bad code sutpid

**Comment by giorno420** [comment]
Suck my fat dick and balls

**Comment by ceilingfans** [comment]
nothing to suck on :troo:

**Comment by giorno420** [comment]
Suck on my spiritual cock

**Comment by ceilingfans** [comment]
still nothing to suck on 😃

**Comment by giorno420** [comment]
Kill yourself then

**Comment by giorno420** [comment]
And why the fuck is the server locked

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
🗿🗿🗿🗿🗿🗿🗿🗿🗿🗿

> And why the fuck is the server locked

**Comment by cheeziess** [comment]
balls 😋

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
can i put my balls in yo jaws 

  😳
👉👈

can i?

**Pull request merged**
